ALTER TABLE ADMIN
    ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(ID);

ALTER TABLE ORIENTATION_ISSUE
    ADD CONSTRAINT CONSTRAINT_E PRIMARY KEY(ID);

ALTER TABLE PROFESSOR
    ADD CONSTRAINT CONSTRAINT_6 PRIMARY KEY(ID);

ALTER TABLE PROFESSOR_INTERESTEDTCCS
    ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(PROFESSOR_ID, TCC_ID);

ALTER TABLE STUDENT
    ADD CONSTRAINT CONSTRAINT_B PRIMARY KEY(ID);

ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT CONSTRAINT_4B PRIMARY KEY(STUDENT_ID, STUDY_AREA_ID);

ALTER TABLE STUDENT_ORIENTATION_INTERESTS
    ADD CONSTRAINT CONSTRAINT_3B PRIMARY KEY(STUDENT_ID, TCC_ID);

ALTER TABLE STUDY_AREA
    ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);

ALTER TABLE TCC
    ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ID);

ALTER TABLE TCCMATCH_USER
    ADD CONSTRAINT CONSTRAINT_C PRIMARY KEY(ID);

ALTER TABLE TCCMATCH_USER_ORIENTATION_ISSUES
    ADD CONSTRAINT CONSTRAINT_2F PRIMARY KEY(TCCMATCH_USER_ID, ORIENTATION_ISSUES_ID);

ALTER TABLE TCCMATCH_USER_ORIENTATION_ISSUES
    ADD CONSTRAINT UK_M2DWGQFAPUDS46FJ84TFBGG20 UNIQUE(ORIENTATION_ISSUES_ID);

ALTER TABLE TCCMATCH_USER_ORIENTATION_ISSUES
    ADD CONSTRAINT FKAGCJO2EQF4VMGPYRF5STM0HGJ FOREIGN KEY(ORIENTATION_ISSUES_ID) REFERENCES ORIENTATION_ISSUE(ID);

ALTER TABLE TCCMATCH_USER_ORIENTATION_ISSUES
    ADD CONSTRAINT FKAA2EXGR3CQJKGXJIIEMGQM89C FOREIGN KEY(TCCMATCH_USER_ID) REFERENCES TCCMATCH_USER(ID);

ALTER TABLE TCC_STUDY_AREAS
    ADD CONSTRAINT FK8M8VU79K3JIJVY77SC3VLRIHW FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID);

ALTER TABLE STUDENT_ORIENTATION_INTERESTS
    ADD CONSTRAINT FK3Y50C4RK638JOWFQ5DOKQM41J FOREIGN KEY(TCC_ID) REFERENCES TCC(ID);

ALTER TABLE TCC_STUDY_AREAS
    ADD CONSTRAINT FK8HSWXQ4BIMTHRDEYW98FO3XYM FOREIGN KEY(TCC_ID) REFERENCES TCC(ID);

ALTER TABLE STUDENT_ORIENTATION_INTERESTS
    ADD CONSTRAINT FKDMVKJ2K84K56JAUX54J81Y2GA FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID);

ALTER TABLE ORIENTATION_ISSUE
    ADD CONSTRAINT FKGL1IRLNUE2R6U2YHNVDYJL2R4 FOREIGN KEY(TCCMATCH_USER_ID) REFERENCES TCCMATCH_USER(ID);

ALTER TABLE ORIENTATION_ISSUE
    ADD CONSTRAINT FKPUPU6PN14WAOS05YNI6OOVG7N FOREIGN KEY(TCC_ID) REFERENCES TCC(ID);

ALTER TABLE PROFESSOR_INTERESTEDTCCS
    ADD CONSTRAINT FKAL6527JR7JXUKHKJP8NV5T0P0 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID);

ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FK2M9QWOB07JNNPYRHAG6S22U2V FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID);

ALTER TABLE STUDENT_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FK7TDYG97AMREE2B40A1SW9U99J FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID);

ALTER TABLE PROFESSOR_LABS
    ADD CONSTRAINT FKTAC37U55JIGWT4P2JPEWK6882 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID);

ALTER TABLE TCCMATCH_USER_EMAILS
    ADD CONSTRAINT FKNRWIUVCQKSHDL168K0W4BSUGQ FOREIGN KEY(TCCMATCH_USER_ID) REFERENCES TCCMATCH_USER(ID);

ALTER TABLE STUDENT
    ADD CONSTRAINT FKE7VNOJBLQ466E89P0BINKUC5I FOREIGN KEY(TCC_ID) REFERENCES TCC(ID);

ALTER TABLE STUDENT
    ADD CONSTRAINT FKEIQ7A06F3JQU2FB5LAGUOGPXC FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID);

ALTER TABLE TCC
    ADD CONSTRAINT FKD3PTQ6PYVOBA45EKS3JELJHI3 FOREIGN KEY(ADVISOR_ID) REFERENCES PROFESSOR(ID);

ALTER TABLE PROFESSOR_INTERESTEDTCCS
    ADD CONSTRAINT FKRXHLS49EMFSUJX1IITWWPPA7R FOREIGN KEY(TCC_ID) REFERENCES TCC(ID);

ALTER TABLE PROFESSOR
    ADD CONSTRAINT FKRKDB5WLWHQX4HTQJD81G52PDL FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID);

ALTER TABLE ADMIN
    ADD CONSTRAINT FK5J7H7V5KHD6DPPKEFET7TIC6P FOREIGN KEY(ID) REFERENCES TCCMATCH_USER(ID);

ALTER TABLE TCC
    ADD CONSTRAINT FKB7RI1NIOFH3RY28BYO0XR954R FOREIGN KEY(ADVISED_STUDENT_ID) REFERENCES STUDENT(ID);

ALTER TABLE PROFESSOR_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FKNIWRUW77XJTWJYOQCW7IH2GSK FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(ID);

ALTER TABLE PROFESSOR_INTERESTED_STUDY_AREAS
    ADD CONSTRAINT FKJM88TNPPO0GFBIVXD3A6MIJAC FOREIGN KEY(STUDY_AREA_ID) REFERENCES STUDY_AREA(ID);